### ISSUE TITLE
ASCII DC1 (0x11) character isn't received

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [martinling/libserialport#26]
I am not able to receive the DC1 (0x11) character using the library. 
Here's the relevant code:
```
enum sp_return error = sp_get_port_by_name("/dev/ttyS0", &port);
if (error == SP_OK) {
    error = sp_open(port, SP_MODE_READ);
    if (error == SP_OK) {
        sp_set_baudrate(port, 115200);
        while (1) {
            usleep(5000); 
            int bytes_waiting = sp_input_waiting(port);
            if (bytes_waiting > 0) {
                unsigned char byte;
                error = sp_nonblocking_read(port, &byte, 1);
                printf("%02X ", byte);
            }
            fflush(stdout);
        }

        sp_close(port);
    } else {
        printf("Error opening serial device\n");
    }
} else {
    printf("Error finding serial device\n");
}
```

It works fine for all most characters but somehow eats up a few control characters like DC1, DC3, DC4. I found this [related stackoverflow question](https://stackoverflow.com/questions/14088606/serial-communication-eats-incoming-ascii-dc1-characters) where the OP had a similar problem which was solved by calling `tcsetattr/tcgetattr` after opening the port.

FWIW, I'm running the code on a LEDE linux ARM embedded system and the same code works fine on a Mac. 
Any idea how I can solve this?

**Comment by martinling** [comment]
Hi, thanks for the report.

When you call `sp_open`, it does do a `tcgetattr` (via internal function `get_config` and then `tcsetattr` (via `set_config`) after opening the port, and clears a lot of termios flags that enable special processing.

The DC1 character is used by software (XON/XOFF) flow control though, and `sp_open` will not turn that off if it is enabled when it opens the port. The policy is for `sp_open` to leave the port with the same main settings it had before (baudrate, data/stop/parity bits, flow control). You then set the port configuration you want after opening it. At the moment you're just setting the baudrate. You should explicitly set all the parameters you want (data bits, parity, stop bits, flow control), otherwise they will just be left at the driver default or whatever was used before.

So I suspect what's happening is that the port is already configured with XON/XOFF flow control enabled when you open it. As such the driver is taking the DC1 as a START control character and ignoring it.

If you call `sp_set_flowcontrol(port, SP_FLOWCONTROL_NONE)` after opening the port, that should stop the behaviour you're seeing.

**Comment by Sufi-Al-Hussaini** [comment]
Thanks a lot @martinling ! Setting flow control to `SP_FLOWCONTROL_NONE` solved the problem.
